### ISSUE TITLE
Request for READMEs data

### ISSUE THREAD

**Issue by hpbl** [gprana/READMEClassifier#1]
Hello,

I've read your paper, and I'm looking into reproducing some of the analysis you've made, and also adding some others I come up with for a school project.

I was wondering if it would be possible to share the READMEs you've acquired from GitHub with me (before they were broken into sections), so I don't have to go through the data collection process.

Thank you.

**Comment by gprana** [comment]
Hi,
Apologies for the late reply. The raw README files are in the input/ReadMes/ directory.
